<?php

$portfolio = [

  'name'    => 'Minoka ',
  'title'   => 'AI/ML & Software Engineer',
  'tagline' => 'Full-spectrum engineer who builds intelligent systems, cross-platform apps, immersive games, and scalable backends — from neural networks to native mobile apps.',
  'email'   => 'minokainduwara@gmail.com',
  'github'  => 'https://github.com/Minokainduwara',
  'linkedin'=> 'https://www.linkedin.com/in/minoka-wickramasinghe-3b7198194/',
  'upwork' => 'https://www.upwork.com/freelancers/~01c066638da7b9262b?mp_source=share',
  'resume'  => 'assets/doc/Resume.pdf',
  // Set to path of your photo e.g. 'assets/img/photo.jpg' or leave empty for placeholder
  'photo'   => 'assets/img/photo.png',

  'typed_texts' => [
    'AI / ML Engineer',
    'Full-Stack Developer',
    'Mobile App Developer',
    'Game Developer',
    'Software Engineer',
    'Deep Learning Expert',
  ],

  'stats' => [
    ['number' => 5,  'suffix' => '+', 'label' => 'Years Experience'],
    ['number' => 50, 'suffix' => '+', 'label' => 'Projects Built'],
    ['number' => 15, 'suffix' => '+', 'label' => 'Technologies'],
    ['number' => 99, 'suffix' => '%', 'label' => 'Dedication'],
  ],

  'about_cards' => [
    ['icon' => '🧠', 'title' => 'AI / ML',         'desc' => 'Deep learning, NLP, computer vision, MLOps'],
    ['icon' => '📱', 'title' => 'Mobile Dev',       'desc' => 'Flutter, React Native, Dart — cross-platform apps'],
    ['icon' => '🌐', 'title' => 'Web & Backend',    'desc' => 'React, Next.js, PHP, Spring Boot, Firebase'],
    ['icon' => '🎮', 'title' => 'Game Development', 'desc' => 'Unity & Unreal Engine, C#, immersive XR'],
    ['icon' => '⚙️', 'title' => 'Systems & IoT',    'desc' => 'C, Arduino, embedded systems, hardware control'],
    ['icon' => '☕', 'title' => 'Enterprise Java',  'desc' => 'Spring Boot, REST APIs, microservices architecture'],
  ],

  // Grouped skill categories for the tabbed skills section
  'skill_categories' => [
    [
      'label'  => 'AI / ML',
      'icon'   => '🧠',
      'skills' => [
        ['name' => 'Python',               'pct' => 98],
        ['name' => 'PyTorch / TensorFlow', 'pct' => 92],
        ['name' => 'HuggingFace',          'pct' => 90],
        ['name' => 'LangChain / RAG',      'pct' => 85],
        ['name' => 'Computer Vision',      'pct' => 87],
        ['name' => 'MLOps / MLflow',       'pct' => 83],
      ],
    ],
    [
      'label'  => 'Web & Backend',
      'icon'   => '🌐',
      'skills' => [
        ['name' => 'React',               'pct' => 93],
        ['name' => 'Next.js',             'pct' => 90],
        ['name' => 'PHP',                 'pct' => 88],
        ['name' => 'Spring Boot (Java)',  'pct' => 85],
        ['name' => 'Firebase',            'pct' => 91],
        ['name' => 'REST APIs',           'pct' => 94],
      ],
    ],
    [
      'label'  => 'Mobile',
      'icon'   => '📱',
      'skills' => [
        ['name' => 'Flutter',           'pct' => 92],
        ['name' => 'Dart',              'pct' => 90],
        ['name' => 'React Native',      'pct' => 87],
        ['name' => 'Firebase (Mobile)', 'pct' => 91],
        ['name' => 'iOS / Android',     'pct' => 85],
      ],
    ],
    [
      'label'  => 'Game Dev',
      'icon'   => '🎮',
      'skills' => [
        ['name' => 'Unity',          'pct' => 88],
        ['name' => 'Unreal Engine',  'pct' => 80],
        ['name' => 'C#',             'pct' => 90],
        ['name' => '3D / XR / AR',   'pct' => 78],
        ['name' => 'Game AI',        'pct' => 82],
      ],
    ],
    [
      'label'  => 'Systems',
      'icon'   => '⚙️',
      'skills' => [
        ['name' => 'Java',              'pct' => 88],
        ['name' => 'C / C++',           'pct' => 84],
        ['name' => 'Arduino',           'pct' => 82],
        ['name' => 'Embedded Systems',  'pct' => 78],
        ['name' => 'Linux / Bash',      'pct' => 86],
      ],
    ],
  ],

  'projects' => [
    [
      'icon'     => '🤖',
      'title'    => 'RAG Chatbot',
      'desc'     => 'A Retrieval-Augmented Generation (RAG) chatbot that answers questions from your own documents using local or cloud-based LLMs.',
      'tags'     => ['Python', 'faiss-cpu', 'HuggingFace', 'LangChain'],
      'category' => 'AI / ML',
      'color'    => '#00ffc8',
      'demo'     => 'https://www.linkedin.com/feed/update/urn:li:activity:7437256389636337664/',
      'code'     => 'https://github.com/Minokainduwara/RAG_Chatbot',
    ],
    [
      'icon'     => '📱',
      'title'    => 'HackTrail Timer',
      'desc'     => 'Cross-platform mobile app built with Flutter & Dart featuring on-device ML inference, Firebase real-time sync, and a stunning adaptive UI.',
      'tags'     => ['Flutter', 'Dart', 'Firebase', 'TFLite'],
      'category' => 'Mobile',
      'color'    => '#7b61ff',
      'demo'     => '#',
      'code'     => 'https://github.com/Minokainduwara/hacktrail_timer',
    ],
    [
      'icon'     => '🌐',
      'title'    => 'Next.js SaaS Dashboard',
      'desc'     => 'Full-stack SaaS platform with Next.js 14, server actions, real-time analytics, role-based auth, and Stripe payments integration.',
      'tags'     => ['Next.js', 'React', 'Firebase', 'PHP'],
      'category' => 'Web',
      'color'    => '#ff4d8d',
      'demo'     => '#',
      'code'     => '#',
    ],
    [
      'icon'     => '🎮',
      'title'    => 'Unity AR Navigation Game',
      'desc'     => 'Augmented reality mobile game built in Unity with real-world GPS-based mechanics, procedural level generation, and multiplayer support.',
      'tags'     => ['Unity', 'C#', 'AR Foundation', 'Firebase'],
      'category' => 'Game Dev',
      'color'    => '#00ffc8',
      'demo'     => '#',
      'code'     => '#',
    ],
    [
      'icon'     => '☕',
      'title'    => 'Spring Boot Microservices',
      'desc'     => 'Scalable microservices backend with Spring Boot, JWT auth, Kafka event streaming, Docker orchestration, and a React admin panel.',
      'tags'     => ['Java', 'Spring Boot', 'Kafka', 'React'],
      'category' => 'Web',
      'color'    => '#7b61ff',
      'demo'     => '#',
      'code'     => '#',
    ],
    [
      'icon'     => '🔍',
      'title'    => 'RAG Search Engine',
      'desc'     => 'Production-grade retrieval-augmented generation system with hybrid search, re-ranking, and multi-modal document understanding over private knowledge bases.',
      'tags'     => ['Python', 'LangChain', 'Pinecone', 'FastAPI'],
      'category' => 'AI / ML',
      'color'    => '#ff4d8d',
      'demo'     => '#',
      'code'     => '#',
    ],
    [
      'icon'     => '⚡',
      'title'    => 'Arduino Smart Home Hub',
      'desc'     => 'IoT smart home controller built with Arduino & C with custom PCB design. Controls lighting, climate, and security with a React Native companion app.',
      'tags'     => ['Arduino', 'C', 'React Native', 'Firebase'],
      'category' => 'Systems',
      'color'    => '#00ffc8',
      'demo'     => '#',
      'code'     => '#',
    ],
    [
      'icon'     => '🎨',
      'title'    => 'Unreal Engine Open World',
      'desc'     => 'Open-world survival game prototype built with Unreal Engine 5 featuring Nanite geometry, Lumen lighting, and AI-driven NPC behaviour trees.',
      'tags'     => ['Unreal Engine', 'C++', 'Blueprints', 'AI'],
      'category' => 'Game Dev',
      'color'    => '#7b61ff',
      'demo'     => '#',
      'code'     => '#',
    ],
    [
      'icon'     => '👁️',
      'title'    => 'Real-Time Object Detection',
      'desc'     => 'Custom YOLOv8-based detection system optimized for edge devices. Achieves 30fps on Jetson Nano with TensorRT quantization and Python REST API.',
      'tags'     => ['Python', 'YOLOv8', 'TensorRT', 'OpenCV'],
      'category' => 'AI / ML',
      'color'    => '#ff4d8d',
      'demo'     => '#',
      'code'     => '#',
    ],
  ],

  'experience' => [
    [
      'date'    => '2023 — Present',
      'role'    => 'Senior AI/ML & Software Engineer',
      'company' => 'Your Company Name',
      'desc'    => 'Leading development of LLM-powered products and full-stack platforms. Built Flutter mobile apps with on-device ML, Next.js dashboards, and Spring Boot microservices serving 500K+ users.',
    ],
    [
      'date'    => '2021 — 2023',
      'role'    => 'Full-Stack & Mobile Developer',
      'company' => 'Previous Company',
      'desc'    => 'Developed cross-platform apps in Flutter and React Native, RESTful backends in PHP and Java Spring Boot, and integrated Firebase for real-time features. Shipped 10+ production apps.',
    ],
    [
      'date'    => '2019 — 2021',
      'role'    => 'Software Engineer & Game Developer',
      'company' => 'First Company',
      'desc'    => 'Built Unity and Unreal Engine games, embedded Arduino systems for IoT prototypes, and contributed to React front-ends and Python data pipelines.',
    ],
  ],
];
